# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5245eeff7e36b9d1ef4152bbb5f450747c016186a2d0bac79421037f63a7d4f9a4254af21ae2a587657af0daac537c3b6b81d0b208fd31d98b6309c1d8629ed1

test:
  secret_key_base: 7252ef32b0931a9e1132a6907a02f34c8190502bf4efacc742210b95516bfb4aacb8c39f2100c2a4bf63c7adb32ee3bf7285cdcc1048d2a8bcf952a7e58df2b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
